from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Notepad(object):
    def setupUi(self, Notepad):
        Notepad.setObjectName("Notepad")
        Notepad.resize(600, 500)
        Notepad.setMinimumSize(QtCore.QSize(600, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./images/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Notepad.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=Notepad)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        Notepad.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Notepad)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(parent=self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuFormat = QtWidgets.QMenu(parent=self.menubar)
        self.menuFormat.setObjectName("menuFormat")
        self.menuAbout = QtWidgets.QMenu(parent=self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        Notepad.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Notepad)
        self.statusbar.setObjectName("statusbar")
        Notepad.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=Notepad)
        self.toolBar.setObjectName("toolBar")
        Notepad.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionNew = QtGui.QAction(parent=Notepad)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./images/new.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionNew.setIcon(icon1)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtGui.QAction(parent=Notepad)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./images/open.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionOpen.setIcon(icon2)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(parent=Notepad)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./images/save.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionSave.setIcon(icon3)
        self.actionSave.setObjectName("actionSave")
        self.actionPrint = QtGui.QAction(parent=Notepad)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./images/print.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionPrint.setIcon(icon4)
        self.actionPrint.setObjectName("actionPrint")
        self.actionPrint_Preview = QtGui.QAction(parent=Notepad)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("./images/printprev.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionPrint_Preview.setIcon(icon5)
        self.actionPrint_Preview.setObjectName("actionPrint_Preview")
        self.actionExport_PDF = QtGui.QAction(parent=Notepad)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("./images/pdf.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionExport_PDF.setIcon(icon6)
        self.actionExport_PDF.setObjectName("actionExport_PDF")
        self.actionQuit = QtGui.QAction(parent=Notepad)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("./images/exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionQuit.setIcon(icon7)
        self.actionQuit.setObjectName("actionQuit")
        self.actionUndo = QtGui.QAction(parent=Notepad)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("./images/undo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionUndo.setIcon(icon8)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtGui.QAction(parent=Notepad)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("./images/redo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionRedo.setIcon(icon9)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCut = QtGui.QAction(parent=Notepad)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("./images/cut.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionCut.setIcon(icon10)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtGui.QAction(parent=Notepad)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("./images/copy.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionCopy.setIcon(icon11)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtGui.QAction(parent=Notepad)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("./images/paste.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionPaste.setIcon(icon12)
        self.actionPaste.setObjectName("actionPaste")
        self.actionBold = QtGui.QAction(parent=Notepad)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("./images/bold.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionBold.setIcon(icon13)
        self.actionBold.setObjectName("actionBold")
        self.actionItalic = QtGui.QAction(parent=Notepad)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("./images/italic.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionItalic.setIcon(icon14)
        self.actionItalic.setObjectName("actionItalic")
        self.actionUnderLine = QtGui.QAction(parent=Notepad)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("./images/underline.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionUnderLine.setIcon(icon15)
        self.actionUnderLine.setObjectName("actionUnderLine")
        self.actionLeft = QtGui.QAction(parent=Notepad)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("./images/left.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionLeft.setIcon(icon16)
        self.actionLeft.setObjectName("actionLeft")
        self.actionRight = QtGui.QAction(parent=Notepad)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("./images/right.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionRight.setIcon(icon17)
        self.actionRight.setObjectName("actionRight")
        self.actionCenter = QtGui.QAction(parent=Notepad)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("./images/center.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionCenter.setIcon(icon18)
        self.actionCenter.setObjectName("actionCenter")
        self.actionJustify = QtGui.QAction(parent=Notepad)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("./images/justify.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionJustify.setIcon(icon19)
        self.actionJustify.setObjectName("actionJustify")
        self.actionFont = QtGui.QAction(parent=Notepad)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("./images/font.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionFont.setIcon(icon20)
        self.actionFont.setObjectName("actionFont")
        self.actionColor = QtGui.QAction(parent=Notepad)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("./images/color.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionColor.setIcon(icon21)
        self.actionColor.setObjectName("actionColor")
        self.actionAbout_Us = QtGui.QAction(parent=Notepad)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("./images/aboutqt.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionAbout_Us.setIcon(icon22)
        self.actionAbout_Us.setObjectName("actionAbout_Us")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionPrint_Preview)
        self.menuFile.addAction(self.actionExport_PDF)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuFormat.addAction(self.actionBold)
        self.menuFormat.addAction(self.actionItalic)
        self.menuFormat.addAction(self.actionUnderLine)
        self.menuFormat.addSeparator()
        self.menuFormat.addAction(self.actionLeft)
        self.menuFormat.addAction(self.actionRight)
        self.menuFormat.addAction(self.actionCenter)
        self.menuFormat.addAction(self.actionJustify)
        self.menuFormat.addSeparator()
        self.menuFormat.addAction(self.actionFont)
        self.menuFormat.addAction(self.actionColor)
        self.menuAbout.addAction(self.actionAbout_Us)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuFormat.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCut)
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addAction(self.actionPaste)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionBold)
        self.toolBar.addAction(self.actionItalic)
        self.toolBar.addAction(self.actionUnderLine)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionColor)
        self.toolBar.addAction(self.actionFont)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPrint)
        self.toolBar.addAction(self.actionPrint_Preview)
        self.toolBar.addSeparator()

        self.retranslateUi(Notepad)
        QtCore.QMetaObject.connectSlotsByName(Notepad)

    def retranslateUi(self, Notepad):
        _translate = QtCore.QCoreApplication.translate
        Notepad.setWindowTitle(_translate("Notepad", "Notepad"))
        self.menuFile.setTitle(_translate("Notepad", "File"))
        self.menuEdit.setTitle(_translate("Notepad", "Edit"))
        self.menuFormat.setTitle(_translate("Notepad", "Format"))
        self.menuAbout.setTitle(_translate("Notepad", "About"))
        self.toolBar.setWindowTitle(_translate("Notepad", "toolBar"))
        self.actionNew.setText(_translate("Notepad", "New"))
        self.actionNew.setShortcut(_translate("Notepad", "Ctrl+N"))
        self.actionOpen.setText(_translate("Notepad", "Open"))
        self.actionOpen.setShortcut(_translate("Notepad", "Ctrl+O"))
        self.actionSave.setText(_translate("Notepad", "Save"))
        self.actionSave.setShortcut(_translate("Notepad", "Ctrl+S"))
        self.actionPrint.setText(_translate("Notepad", "Print"))
        self.actionPrint.setShortcut(_translate("Notepad", "Ctrl+P"))
        self.actionPrint_Preview.setText(_translate("Notepad", "Print Preview"))
        self.actionPrint_Preview.setShortcut(_translate("Notepad", "Ctrl+Shift+P"))
        self.actionExport_PDF.setText(_translate("Notepad", "Export PDF"))
        self.actionExport_PDF.setShortcut(_translate("Notepad", "Ctrl+Alt+Shift+P"))
        self.actionQuit.setText(_translate("Notepad", "Quit"))
        self.actionQuit.setShortcut(_translate("Notepad", "Ctrl+Q"))
        self.actionUndo.setText(_translate("Notepad", "Undo"))
        self.actionUndo.setShortcut(_translate("Notepad", "Ctrl+Z"))
        self.actionRedo.setText(_translate("Notepad", "Redo"))
        self.actionRedo.setShortcut(_translate("Notepad", "Ctrl+Y"))
        self.actionCut.setText(_translate("Notepad", "Cut"))
        self.actionCut.setShortcut(_translate("Notepad", "Ctrl+X"))
        self.actionCopy.setText(_translate("Notepad", "Copy"))
        self.actionCopy.setShortcut(_translate("Notepad", "Ctrl+C"))
        self.actionPaste.setText(_translate("Notepad", "Paste"))
        self.actionPaste.setShortcut(_translate("Notepad", "Ctrl+V"))
        self.actionBold.setText(_translate("Notepad", "Bold"))
        self.actionBold.setShortcut(_translate("Notepad", "Ctrl+B"))
        self.actionItalic.setText(_translate("Notepad", "Italic"))
        self.actionItalic.setShortcut(_translate("Notepad", "Ctrl+I"))
        self.actionUnderLine.setText(_translate("Notepad", "UnderLine"))
        self.actionUnderLine.setShortcut(_translate("Notepad", "Ctrl+U"))
        self.actionLeft.setText(_translate("Notepad", "Left"))
        self.actionLeft.setShortcut(_translate("Notepad", "Ctrl+J"))
        self.actionRight.setText(_translate("Notepad", "Right"))
        self.actionRight.setShortcut(_translate("Notepad", "Ctrl+K"))
        self.actionCenter.setText(_translate("Notepad", "Center"))
        self.actionCenter.setShortcut(_translate("Notepad", "Ctrl+L"))
        self.actionJustify.setText(_translate("Notepad", "Justify"))
        self.actionJustify.setShortcut(_translate("Notepad", "Ctrl+Shift+J"))
        self.actionFont.setText(_translate("Notepad", "Font"))
        self.actionFont.setShortcut(_translate("Notepad", "Ctrl+F"))
        self.actionColor.setText(_translate("Notepad", "Color"))
        self.actionColor.setShortcut(_translate("Notepad", "Ctrl+Shift+C"))
        self.actionAbout_Us.setText(_translate("Notepad", "About Us"))
        self.actionAbout_Us.setShortcut(_translate("Notepad", "Ctrl+Shift+A"))


